#!/bin/sh

# this script was pinched from Simon Coffey:
# https://github.com/urbanautomaton/dotfiles/blob/e8a37d16f7eb7326a522fb5685e9926861a84362/install.sh

set -euo pipefail

readonly DOTFILES="
  gemrc
  gitconfig
  gitignore_global
  zshrc
"

for file in $DOTFILES; do
  if [[ -n "$file" ]]; then
    ln -sf ~/dotfiles/$file ~/.$file
  fi
done
