#!/bin/sh

# this script was pinched from Simon Coffey:
# https://github.com/urbanautomaton/dotfiles/blob/e8a37d16f7eb7326a522fb5685e9926861a84362/install.sh
# once, it was as good, now, it's a bastardization

set -euo pipefail

readonly DOTFILES="
  gemrc
  gitconfig
  gitignore_global
  vimrc
  zshrc
  npmrc
"

for file in $DOTFILES; do
  if [[ -n "$file" ]]; then
    ln -sf ~/dotfiles/$file ~/.$file
  fi
done

# vs code
ln -sf ~/dotfiles/vscode_settings.json "$HOME/Library/Application Support/Code/User/settings.json"

# karabiner
mkdir -p ~/.config/karabiner
ln -sf ~/dotfiles/karabiner.json ~/.config/karabiner
